package com.example.conference.dao.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.util.Date;

@Entity
@Getter
@Setter
public class Participant {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String nom;
    private String email;
    private String photo;

    @Enumerated(EnumType.STRING) // Specify how to persist the Enum
    private Genre genre;

    @OneToOne(cascade = CascadeType.ALL) // Consider cascade options
    private Commentaire commentaire;


    public Participant() {
        // Default constructor required by JPA
    }

    // Constructors, getters, and setters will be generated by Lombok's @Getter and @Setter

    // You can also add methods
}